Try out OIDC

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -1,6 +1,3 @@
-# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
-# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
-
 name: Java CI with Maven
 
 on:
@@ -11,6 +8,8 @@ on:
 
 jobs:
   build:
+    permissions:
+      id-token: write
 
     runs-on: ubuntu-latest
 
@@ -22,5 +21,16 @@ jobs:
         java-version: '11'
         distribution: 'temurin'
         cache: maven
+    - name: Detect the builder ref
+      id: detect
+      shell: bash
+      run: |
+        status_code=$(curl -sS -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=protocol7/slsa-java" -o jwt.json -w '%{http_code}')
+        if [[ $status_code -ge 400 ]]; then
+            error_msg=$(jq -r .message jwt.json 2>/dev/null || echo 'unknown error')
+            echo "Failed to get OIDC token from GitHub, response $status_code: $error_msg"
+            exit 1;
+        fi
+        cat jwt.json | jq -r '.value'
     - name: Build with Maven
       run: mvn -B package
